#
#  Licensed to the Apache Software Foundation (ASF) under one or more
#  contributor license agreements. See the NOTICE file distributed with
#  this work for additional information regarding copyright ownership.
#  The ASF licenses this file to You under the Apache License, Version 2.0
#  (the "License"); you may not use this file except in compliance with
#  the License. You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
name: "Dump Github Cache"

on:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dumpy:
    runs-on: ubuntu-latest
    steps:
      - name: 'Check out repository'
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: 'Cache Maven packages'
        uses: ./.github/actions/common/cache-maven-packages
      - name: Setup Java
        uses: ./.github/actions/common/setup-java
      - name: 'Dump repo before'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo Dump repo before
          (find ~/.m2/ | grep kroxy) || true
      - name: 'Do some maven stuff that will put maven artefacts into cache (kroxy and others)'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn install -pl kroxylicious-krpc-plugin -am -DskipTests
      - name: 'Dump repo after'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo Dump repo after
          (find ~/.m2/ | grep kroxy) || true

